Fixed docker analysis with trivy

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,7 +15,7 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@v2
 
       - name: Build Docker image
         run: |
@@ -26,11 +26,18 @@ jobs:
           docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
             -v ${{ github.workspace }}/trivy-cache/:/root/.cache/ \
             -v ${{ github.workspace }}/sonarqube.tpl:/input/sonarqube.tpl \
-            -v ${{ github.workspace }}/trivy-output:/output aquasec/trivy \
-            image --exit-code 1 --no-progress \
+            -v ${{ github.workspace }}:/workspace aquasec/trivy \
+            image --exit-code 0 --no-progress \
             --format template --template "@/input/sonarqube.tpl" \
-            -o trivy-report.json \
+            -o /workspace/trivy-report.json \
             my-docker-image:latest || true
+
+      - name: List workspace directory
+        run: ls -la ${{ github.workspace }}
+
+      - name: Check Trivy report
+        run: |
+          cat ${{ github.workspace }}/trivy-report.json || echo "Trivy report not found"
 
       - name: Upload Trivy report
         uses: actions/upload-artifact@v2
